version: '3.8'

services:
  app:
    image: node:20
    working_dir: /usr/src/app
    environment:
      - PORT=9000
      - MODEL_URL=${MODEL_URL}
      - BUCKET_IMAGES=${BUCKET_IMAGES}
      - GCP_PROJECT_ID=${GCP_PROJECT_ID}
      # Replace 'REDACTED' with actual value of Google AI Studio API KEY
      - GOOGLE_API_KEY=REDACTED
    volumes:
      - .:/usr/src/app
    ports:
      - "9000:9000"
    command: >
      sh -c "
      npm install &&
      npm run start:prod
      "
    env_file:
      - .env.prod
